#!/usr/bin/env bash
# coding: utf-8
'''
@project: ConjugadorDE <github.com/memoriadecalculo/ConjugadorDE>
@copyright: Memória de Cálculo (c) 2023 <memoriadcalculo@gmail.com>
'''
# ----------------------------------------------------------------------------
# http://www.verbix.com/
# Conjugador de verbos Verbix.
# Consulta via web a conjugação do verbo solicitado e cadastra numa base de
# dados local. Somente utiliza a internet quando necessário.
#
# Idiomas cadastrados são:
#      pt = português         fr = francês
#      en = inglês            de = alemão
#
# Uso: zzconjugador idioma "verbo no infinitivo"
# Ex.: zzconjugador pt comprar            # conjuga em pt o verbo comprar
#      zzconjugador de kaufen             # conjuga em alemão o verbo kaufen
#      zzconjugador en buy                # conjuga em inglês o verbo buy
#
# Autor: Memória de Cálculo <memoriadcalculo@gmail.com>
# Desde: 2011-12-13
# Versão: 1
# Licença: MIT
# ----------------------------------------------------------------------------
zzconjugador ()
{
	zzzz -h conjugador $1 && return

	[ "$1" ] || { zztool uso conjugador; return 1; }

	# Variaveis locais
	local padrao
	local url='http://www.verbix.com/'
	local lang_de='pt'
	local lang_para='en'
	local charset_de='ISO-8859-1'
	local charset_para='UTF-8'
	local audio_file="/tmp/$$.WAV"
	local play_cmd='mpg123 -q'

	case "$1" in
		# O usuário informou um par de idiomas, como pt-en
		[a-z][a-z]-[a-z][a-z])
			lang_de=${1%-??}
			lang_para=${1#??-}
			shift
		;;
		-l | --lista)
			# Uma tag por linha, então extrai e formata as opções do <SELECT>
			$ZZWWWHTML "$url" |
				awk 'gsub("<", "\n&")' |
				sed -n '
					/^<select id=gt-sl /, /^<\/select>/ {
						s/zh-CN/cn/
						s/.*value="\(..\)">\(.*\)/\1 = \2/p
					}' |
				# O código da página vem em ISO em vez de UTF-8 :/
				iconv --from-code=$charset_de --to-code=$charset_para |
				# Filtra a lista com o texto de pesquisa, ou mostra ela toda
				grep ${2:-=}
			return
		;;
		-a | --audio)
			# Narrativa
				shift
			        padrao=$(echo "$*" | sed "$ZZSEDURL")
			        local audio="translate_tts?ie=$charset_para&q=$padrao&tl=pt&prev=input"
				$ZZWWWHTML "$url/$audio" > $audio_file && $play_cmd $audio_file && rm -rf $audio_file
				return
		;;
	esac

	padrao=$(echo "$*" | sed "$ZZSEDURL")

	# Exceção para o chinês, que usa um código diferente
	test $lang_para = 'cn' && lang_para='zh-CN'
	
	# Baixa a URL, coloca cada tag em uma linha, pega a linha desejada
	# e limpa essa linha para estar somente o texto desejado.
	$ZZWWWHTML "$url?tr=$lang_de&hl=$lang_para&text=$padrao" |
		iconv --from-code=$charset_de --to-code=$charset_para |
		awk 'gsub("<[^/]", "\n&")' |
		grep '<span title' |
		sed 's/<[^>]*>//g'
}